#!/bin/sh

# Fix ssh agent forwarding socket for a reattached screen session

# Reference:
# SSH agent forwarding and screen, https://gist.github.com/martijnvermaat/8070533

if test "$SSH_AUTH_SOCK" ; then
    ln -sf $SSH_AUTH_SOCK ~/.ssh/ssh_auth_sock
fi

# Existing ~/.ssh/rc will problem with X11 forwarding.
# According to sshd manpage, if there exists ~/.ssh/rc, xauth will not executed,
# so we have to execute xauth by own hand.

# Taken from the sshd(8) manpage.
if read proto cookie && [ -n "$DISPLAY" ]; then
    if [ `echo $DISPLAY | cut -c1-10` = 'localhost:' ]; then
        # X11UseLocalhost=yes
        echo add unix:`echo $DISPLAY |
                            cut -c11-` $proto $cookie
    else
        # X11UseLocalhost=no
        echo add $DISPLAY $proto $cookie
    fi | xauth -q -
fi
